#pragma once

#ifndef RENEGADE_RENDERER_TYPES_DEFINED
#define RENEGADE_RENDERER_TYPES_DEFINED
#endif

#include "renegade_build_config.h"

#include <cstdint>

#ifndef TRUE
#define TRUE 1
#endif

#ifndef FALSE
#define FALSE 0
#endif

#ifndef CONST
#define CONST const
#endif

#ifndef SUCCEEDED
#define SUCCEEDED(hr) ((hr) >= 0)
#endif

#ifndef FAILED
#define FAILED(hr) ((hr) < 0)
#endif

using BOOL = int;
using BYTE = std::uint8_t;
using WORD = std::uint16_t;
using DWORD = std::uint32_t;
using UINT = std::uint32_t;
using ULONG = std::uint32_t;
using HRESULT = int;
using D3DCOLOR = std::uint32_t;

using HWND = void *;
using HINSTANCE = void *;

struct RECT;
struct POINT;

struct D3DVECTOR
{
    float x;
    float y;
    float z;
};

struct D3DCOLORVALUE
{
    float r;
    float g;
    float b;
    float a;
};

struct D3DVIEWPORT8
{
    DWORD X;
    DWORD Y;
    DWORD Width;
    DWORD Height;
    float MinZ;
    float MaxZ;
};

struct D3DMATERIAL8
{
    D3DCOLORVALUE Diffuse;
    D3DCOLORVALUE Ambient;
    D3DCOLORVALUE Specular;
    D3DCOLORVALUE Emissive;
    float Power;
};

using D3DLIGHTTYPE = std::uint32_t;
constexpr D3DLIGHTTYPE D3DLIGHT_POINT = 1;
constexpr D3DLIGHTTYPE D3DLIGHT_SPOT = 2;
constexpr D3DLIGHTTYPE D3DLIGHT_DIRECTIONAL = 3;

struct D3DLIGHT8
{
    D3DLIGHTTYPE Type;
    D3DCOLORVALUE Diffuse;
    D3DCOLORVALUE Specular;
    D3DCOLORVALUE Ambient;
    D3DVECTOR Position;
    D3DVECTOR Direction;
    float Range;
    float Falloff;
    float Attenuation0;
    float Attenuation1;
    float Attenuation2;
    float Theta;
    float Phi;
};

struct RendererGuid
{
    std::uint32_t Data1;
    std::uint16_t Data2;
    std::uint16_t Data3;
    std::uint8_t Data4[8];
};

struct RendererVersion64
{
    std::uint32_t LowPart;
    std::uint32_t HighPart;
};

struct D3DADAPTER_IDENTIFIER8
{
    char Driver[512];
    char Description[512];
    char DeviceName[32];
    std::uint64_t DriverVersionRaw;
    std::uint32_t VendorId;
    std::uint32_t DeviceId;
    std::uint32_t SubSysId;
    std::uint32_t Revision;
    RendererGuid DeviceIdentifier;
    std::uint32_t WHQLLevel;

    RendererVersion64 DriverVersion;
};

using D3DDEVTYPE = std::uint32_t;
constexpr D3DDEVTYPE D3DDEVTYPE_HAL = 1;

using D3DFORMAT = std::uint32_t;
constexpr D3DFORMAT D3DFMT_UNKNOWN = 0;
constexpr D3DFORMAT D3DFMT_R8G8B8 = 20;
constexpr D3DFORMAT D3DFMT_A8R8G8B8 = 21;
constexpr D3DFORMAT D3DFMT_X8R8G8B8 = 22;
constexpr D3DFORMAT D3DFMT_R5G6B5 = 23;
constexpr D3DFORMAT D3DFMT_X1R5G5B5 = 24;
constexpr D3DFORMAT D3DFMT_A1R5G5B5 = 25;
constexpr D3DFORMAT D3DFMT_A4R4G4B4 = 26;
constexpr D3DFORMAT D3DFMT_R3G3B2 = 27;
constexpr D3DFORMAT D3DFMT_A8 = 28;
constexpr D3DFORMAT D3DFMT_A8R3G3B2 = 29;
constexpr D3DFORMAT D3DFMT_X4R4G4B4 = 30;
constexpr D3DFORMAT D3DFMT_A4L4 = 31;
constexpr D3DFORMAT D3DFMT_A8P8 = 40;
constexpr D3DFORMAT D3DFMT_P8 = 41;
constexpr D3DFORMAT D3DFMT_L8 = 50;
constexpr D3DFORMAT D3DFMT_A8L8 = 51;
constexpr D3DFORMAT D3DFMT_V8U8 = 60;
constexpr D3DFORMAT D3DFMT_L6V5U5 = 61;
constexpr D3DFORMAT D3DFMT_X8L8V8U8 = 62;
constexpr D3DFORMAT D3DFMT_Q8W8V8U8 = 63;
constexpr D3DFORMAT D3DFMT_V16U16 = 64;
constexpr D3DFORMAT D3DFMT_W11V11U10 = 65;
constexpr D3DFORMAT D3DFMT_YUY2 = 100;
constexpr D3DFORMAT D3DFMT_UYVY = 101;
constexpr D3DFORMAT D3DFMT_DXT1 = 0x31545844;
constexpr D3DFORMAT D3DFMT_DXT2 = 0x32545844;
constexpr D3DFORMAT D3DFMT_DXT3 = 0x33545844;
constexpr D3DFORMAT D3DFMT_DXT4 = 0x34545844;
constexpr D3DFORMAT D3DFMT_DXT5 = 0x35545844;
constexpr D3DFORMAT D3DFMT_D16_LOCKABLE = 70;
constexpr D3DFORMAT D3DFMT_D32 = 71;
constexpr D3DFORMAT D3DFMT_D15S1 = 73;
constexpr D3DFORMAT D3DFMT_D24S8 = 75;
constexpr D3DFORMAT D3DFMT_D16 = 80;
constexpr D3DFORMAT D3DFMT_D24X8 = 77;
constexpr D3DFORMAT D3DFMT_D24X4S4 = 79;
constexpr D3DFORMAT D3DFMT_INDEX16 = 101;

using D3DPOOL = std::uint32_t;
constexpr D3DPOOL D3DPOOL_DEFAULT = 0;
constexpr D3DPOOL D3DPOOL_MANAGED = 1;
constexpr D3DPOOL D3DPOOL_SYSTEMMEM = 2;

using D3DTEXTUREADDRESS = std::uint32_t;
constexpr D3DTEXTUREADDRESS D3DTADDRESS_WRAP = 1;
constexpr D3DTEXTUREADDRESS D3DTADDRESS_CLAMP = 3;

using D3DPRIMITIVETYPE = std::uint32_t;
constexpr D3DPRIMITIVETYPE D3DPT_TRIANGLELIST = 0;
constexpr D3DPRIMITIVETYPE D3DPT_TRIANGLESTRIP = 1;
constexpr D3DPRIMITIVETYPE D3DPT_TRIANGLEFAN = 2;

using D3DTRANSFORMSTATETYPE = std::uint32_t;
constexpr D3DTRANSFORMSTATETYPE D3DTS_WORLD = 0;
constexpr D3DTRANSFORMSTATETYPE D3DTS_VIEW = 2;
constexpr D3DTRANSFORMSTATETYPE D3DTS_PROJECTION = 3;
constexpr D3DTRANSFORMSTATETYPE D3DTS_TEXTURE0 = 16;
constexpr D3DTRANSFORMSTATETYPE D3DTS_TEXTURE1 = 17;
constexpr D3DTRANSFORMSTATETYPE D3DTS_TEXTURE2 = 18;
constexpr D3DTRANSFORMSTATETYPE D3DTS_TEXTURE3 = 19;
constexpr D3DTRANSFORMSTATETYPE D3DTS_TEXTURE4 = 20;
constexpr D3DTRANSFORMSTATETYPE D3DTS_TEXTURE5 = 21;
constexpr D3DTRANSFORMSTATETYPE D3DTS_TEXTURE6 = 22;
constexpr D3DTRANSFORMSTATETYPE D3DTS_TEXTURE7 = 23;
constexpr D3DTRANSFORMSTATETYPE D3DTS_WORLDMATRIX = 256;
constexpr D3DTRANSFORMSTATETYPE D3DTS_FORCE_DWORD = 0x7fffffff;

using D3DRENDERSTATETYPE = std::uint32_t;
constexpr D3DRENDERSTATETYPE D3DRS_ZENABLE = 0;
constexpr D3DRENDERSTATETYPE D3DRS_FILLMODE = 1;
constexpr D3DRENDERSTATETYPE D3DRS_SHADEMODE = 2;
constexpr D3DRENDERSTATETYPE D3DRS_ZWRITEENABLE = 3;
constexpr D3DRENDERSTATETYPE D3DRS_ALPHATESTENABLE = 4;
constexpr D3DRENDERSTATETYPE D3DRS_LASTPIXEL = 5;
constexpr D3DRENDERSTATETYPE D3DRS_SRCBLEND = 6;
constexpr D3DRENDERSTATETYPE D3DRS_DESTBLEND = 7;
constexpr D3DRENDERSTATETYPE D3DRS_CULLMODE = 8;
constexpr D3DRENDERSTATETYPE D3DRS_ZFUNC = 9;
constexpr D3DRENDERSTATETYPE D3DRS_ALPHAREF = 10;
constexpr D3DRENDERSTATETYPE D3DRS_ALPHAFUNC = 11;
constexpr D3DRENDERSTATETYPE D3DRS_DITHERENABLE = 12;
constexpr D3DRENDERSTATETYPE D3DRS_ALPHABLENDENABLE = 13;
constexpr D3DRENDERSTATETYPE D3DRS_FOGENABLE = 14;
constexpr D3DRENDERSTATETYPE D3DRS_SPECULARENABLE = 15;
constexpr D3DRENDERSTATETYPE D3DRS_FOGCOLOR = 16;
constexpr D3DRENDERSTATETYPE D3DRS_FOGTABLEMODE = 17;
constexpr D3DRENDERSTATETYPE D3DRS_FOGSTART = 18;
constexpr D3DRENDERSTATETYPE D3DRS_FOGEND = 19;
constexpr D3DRENDERSTATETYPE D3DRS_FOGDENSITY = 20;
constexpr D3DRENDERSTATETYPE D3DRS_EDGEANTIALIAS = 21;
constexpr D3DRENDERSTATETYPE D3DRS_ZBIAS = 22;
constexpr D3DRENDERSTATETYPE D3DRS_RANGEFOGENABLE = 23;
constexpr D3DRENDERSTATETYPE D3DRS_STENCILENABLE = 24;
constexpr D3DRENDERSTATETYPE D3DRS_STENCILFAIL = 25;
constexpr D3DRENDERSTATETYPE D3DRS_STENCILZFAIL = 26;
constexpr D3DRENDERSTATETYPE D3DRS_STENCILPASS = 27;
constexpr D3DRENDERSTATETYPE D3DRS_STENCILFUNC = 28;
constexpr D3DRENDERSTATETYPE D3DRS_STENCILREF = 29;
constexpr D3DRENDERSTATETYPE D3DRS_STENCILMASK = 30;
constexpr D3DRENDERSTATETYPE D3DRS_STENCILWRITEMASK = 31;
constexpr D3DRENDERSTATETYPE D3DRS_TEXTUREFACTOR = 32;
constexpr D3DRENDERSTATETYPE D3DRS_WRAP0 = 33;
constexpr D3DRENDERSTATETYPE D3DRS_WRAP1 = 34;
constexpr D3DRENDERSTATETYPE D3DRS_WRAP2 = 35;
constexpr D3DRENDERSTATETYPE D3DRS_WRAP3 = 36;
constexpr D3DRENDERSTATETYPE D3DRS_WRAP4 = 37;
constexpr D3DRENDERSTATETYPE D3DRS_WRAP5 = 38;
constexpr D3DRENDERSTATETYPE D3DRS_WRAP6 = 39;
constexpr D3DRENDERSTATETYPE D3DRS_WRAP7 = 40;
constexpr D3DRENDERSTATETYPE D3DRS_CLIPPING = 41;
constexpr D3DRENDERSTATETYPE D3DRS_LIGHTING = 42;
constexpr D3DRENDERSTATETYPE D3DRS_AMBIENT = 43;
constexpr D3DRENDERSTATETYPE D3DRS_FOGVERTEXMODE = 44;
constexpr D3DRENDERSTATETYPE D3DRS_COLORVERTEX = 45;
constexpr D3DRENDERSTATETYPE D3DRS_LOCALVIEWER = 46;
constexpr D3DRENDERSTATETYPE D3DRS_NORMALIZENORMALS = 47;
constexpr D3DRENDERSTATETYPE D3DRS_DIFFUSEMATERIALSOURCE = 48;
constexpr D3DRENDERSTATETYPE D3DRS_SPECULARMATERIALSOURCE = 49;
constexpr D3DRENDERSTATETYPE D3DRS_AMBIENTMATERIALSOURCE = 50;
constexpr D3DRENDERSTATETYPE D3DRS_EMISSIVEMATERIALSOURCE = 51;
constexpr D3DRENDERSTATETYPE D3DRS_VERTEXBLEND = 52;
constexpr D3DRENDERSTATETYPE D3DRS_CLIPPLANEENABLE = 53;
constexpr D3DRENDERSTATETYPE D3DRS_POINTSIZE = 54;
constexpr D3DRENDERSTATETYPE D3DRS_POINTSIZE_MIN = 55;
constexpr D3DRENDERSTATETYPE D3DRS_POINTSPRITEENABLE = 56;
constexpr D3DRENDERSTATETYPE D3DRS_POINTSCALEENABLE = 57;
constexpr D3DRENDERSTATETYPE D3DRS_POINTSCALE_A = 58;
constexpr D3DRENDERSTATETYPE D3DRS_POINTSCALE_B = 59;
constexpr D3DRENDERSTATETYPE D3DRS_POINTSCALE_C = 60;
constexpr D3DRENDERSTATETYPE D3DRS_MULTISAMPLEANTIALIAS = 61;
constexpr D3DRENDERSTATETYPE D3DRS_MULTISAMPLEMASK = 62;
constexpr D3DRENDERSTATETYPE D3DRS_PATCHEDGESTYLE = 63;
constexpr D3DRENDERSTATETYPE D3DRS_DEBUGMONITORTOKEN = 64;
constexpr D3DRENDERSTATETYPE D3DRS_POINTSIZE_MAX = 65;
constexpr D3DRENDERSTATETYPE D3DRS_INDEXEDVERTEXBLENDENABLE = 66;
constexpr D3DRENDERSTATETYPE D3DRS_COLORWRITEENABLE = 67;
constexpr D3DRENDERSTATETYPE D3DRS_TWEENFACTOR = 68;
constexpr D3DRENDERSTATETYPE D3DRS_BLENDOP = 69;
constexpr D3DRENDERSTATETYPE D3DRS_POSITIONORDER = 70;
constexpr D3DRENDERSTATETYPE D3DRS_NORMALORDER = 71;
constexpr D3DRENDERSTATETYPE D3DRS_SOFTWAREVERTEXPROCESSING = 72;
constexpr D3DRENDERSTATETYPE D3DRS_PATCHSEGMENTS = 73;
constexpr D3DRENDERSTATETYPE D3DRS_ZVISIBLE = 74;
constexpr D3DRENDERSTATETYPE D3DRS_LINEPATTERN = 75;

using D3DTEXTURESTAGESTATETYPE = std::uint32_t;
using D3DTEXTUREOP = DWORD;
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_COLOROP = 0;
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_COLORARG1 = 1;
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_COLORARG2 = 2;
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_ALPHAOP = 3;
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_ALPHAARG1 = 4;
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_ALPHAARG2 = 5;
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_BUMPENVMAT00 = 6;
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_BUMPENVMAT01 = 7;
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_BUMPENVMAT10 = 8;
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_BUMPENVMAT11 = 9;
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_TEXCOORDINDEX = 10;
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_BUMPENVLSCALE = 11;
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_BUMPENVLOFFSET = 12;
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_TEXTURETRANSFORMFLAGS = 13;
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_COLORARG0 = 14;
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_ALPHAARG0 = 15;
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_RESULTARG = 16;
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_ADDRESSU = 17;
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_ADDRESSV = 18;
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_BORDERCOLOR = 19;
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_MAGFILTER = 20;
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_MINFILTER = 21;
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_MIPFILTER = 22;
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_MIPMAPLODBIAS = 23;
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_MAXMIPLEVEL = 24;
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_MAXANISOTROPY = 25;
constexpr D3DTEXTURESTAGESTATETYPE D3DTSS_ADDRESSW = 26;

using D3DCMPFUNC = std::uint32_t;
constexpr D3DCMPFUNC D3DCMP_NEVER = 0;
constexpr D3DCMPFUNC D3DCMP_LESS = 1;
constexpr D3DCMPFUNC D3DCMP_EQUAL = 2;
constexpr D3DCMPFUNC D3DCMP_LESSEQUAL = 3;
constexpr D3DCMPFUNC D3DCMP_GREATER = 4;
constexpr D3DCMPFUNC D3DCMP_NOTEQUAL = 5;
constexpr D3DCMPFUNC D3DCMP_GREATEREQUAL = 6;
constexpr D3DCMPFUNC D3DCMP_ALWAYS = 7;

using D3DBLEND = std::uint32_t;
constexpr D3DBLEND D3DBLEND_ZERO = 0;
constexpr D3DBLEND D3DBLEND_ONE = 1;
constexpr D3DBLEND D3DBLEND_SRCCOLOR = 2;
constexpr D3DBLEND D3DBLEND_INVSRCCOLOR = 3;
constexpr D3DBLEND D3DBLEND_SRCALPHA = 4;
constexpr D3DBLEND D3DBLEND_INVSRCALPHA = 5;
constexpr D3DBLEND D3DBLEND_DESTALPHA = 6;
constexpr D3DBLEND D3DBLEND_INVDESTALPHA = 7;
constexpr D3DBLEND D3DBLEND_DESTCOLOR = 8;
constexpr D3DBLEND D3DBLEND_INVDESTCOLOR = 9;
constexpr D3DBLEND D3DBLEND_SRCALPHASAT = 10;
constexpr D3DBLEND D3DBLEND_BOTHSRCALPHA = 11;
constexpr D3DBLEND D3DBLEND_BOTHINVSRCALPHA = 12;

using D3DBLENDOP = std::uint32_t;
constexpr D3DBLENDOP D3DBLENDOP_ADD = 0;
constexpr D3DBLENDOP D3DBLENDOP_SUBTRACT = 1;
constexpr D3DBLENDOP D3DBLENDOP_REVSUBTRACT = 2;
constexpr D3DBLENDOP D3DBLENDOP_MIN = 3;
constexpr D3DBLENDOP D3DBLENDOP_MAX = 4;

using D3DFOGMODE = std::uint32_t;
constexpr D3DFOGMODE D3DFOG_NONE = 0;
constexpr D3DFOGMODE D3DFOG_EXP = 1;
constexpr D3DFOGMODE D3DFOG_EXP2 = 2;
constexpr D3DFOGMODE D3DFOG_LINEAR = 3;

using D3DCULL = std::uint32_t;
constexpr D3DCULL D3DCULL_NONE = 1;
constexpr D3DCULL D3DCULL_CW = 2;
constexpr D3DCULL D3DCULL_CCW = 3;

using D3DFILLMODE = std::uint32_t;
constexpr D3DFILLMODE D3DFILL_POINT = 0;
constexpr D3DFILLMODE D3DFILL_WIREFRAME = 1;
constexpr D3DFILLMODE D3DFILL_SOLID = 2;

using D3DSHADEMODE = std::uint32_t;
constexpr D3DSHADEMODE D3DSHADE_FLAT = 0;
constexpr D3DSHADEMODE D3DSHADE_GOURAUD = 1;
constexpr D3DSHADEMODE D3DSHADE_PHONG = 2;

using D3DSTENCILOP = std::uint32_t;
constexpr D3DSTENCILOP D3DSTENCILOP_KEEP = 0;
constexpr D3DSTENCILOP D3DSTENCILOP_ZERO = 1;
constexpr D3DSTENCILOP D3DSTENCILOP_REPLACE = 2;
constexpr D3DSTENCILOP D3DSTENCILOP_INCRSAT = 3;
constexpr D3DSTENCILOP D3DSTENCILOP_DECRSAT = 4;
constexpr D3DSTENCILOP D3DSTENCILOP_INVERT = 5;
constexpr D3DSTENCILOP D3DSTENCILOP_INCR = 6;
constexpr D3DSTENCILOP D3DSTENCILOP_DECR = 7;

constexpr DWORD D3DTOP_DISABLE = 0;
constexpr DWORD D3DTOP_SELECTARG1 = 1;
constexpr DWORD D3DTOP_SELECTARG2 = 2;
constexpr DWORD D3DTOP_MODULATE = 3;
constexpr DWORD D3DTOP_MODULATE2X = 4;
constexpr DWORD D3DTOP_MODULATE4X = 5;
constexpr DWORD D3DTOP_ADD = 6;
constexpr DWORD D3DTOP_ADDSIGNED = 7;
constexpr DWORD D3DTOP_ADDSIGNED2X = 8;
constexpr DWORD D3DTOP_SUBTRACT = 9;
constexpr DWORD D3DTOP_ADDSMOOTH = 10;
constexpr DWORD D3DTOP_BLENDDIFFUSEALPHA = 11;
constexpr DWORD D3DTOP_BLENDTEXTUREALPHA = 12;
constexpr DWORD D3DTOP_BLENDFACTORALPHA = 13;
constexpr DWORD D3DTOP_BLENDTEXTUREALPHAPM = 14;
constexpr DWORD D3DTOP_BLENDCURRENTALPHA = 15;
constexpr DWORD D3DTOP_PREMODULATE = 16;
constexpr DWORD D3DTOP_MODULATEALPHA_ADDCOLOR = 17;
constexpr DWORD D3DTOP_MODULATECOLOR_ADDALPHA = 18;
constexpr DWORD D3DTOP_MODULATEINVALPHA_ADDCOLOR = 19;
constexpr DWORD D3DTOP_MODULATEINVCOLOR_ADDALPHA = 20;
constexpr DWORD D3DTOP_BUMPENVMAP = 21;
constexpr DWORD D3DTOP_BUMPENVMAPLUMINANCE = 22;
constexpr DWORD D3DTOP_DOTPRODUCT3 = 23;
constexpr DWORD D3DTOP_MULTIPLYADD = 24;
constexpr DWORD D3DTOP_LERP = 25;

constexpr DWORD D3DTA_SELECTMASK = 0x0f;
constexpr DWORD D3DTA_DIFFUSE = 0x00;
constexpr DWORD D3DTA_CURRENT = 0x01;
constexpr DWORD D3DTA_TEXTURE = 0x02;
constexpr DWORD D3DTA_TFACTOR = 0x03;
constexpr DWORD D3DTA_SPECULAR = 0x04;
constexpr DWORD D3DTA_TEMP = 0x05;
constexpr DWORD D3DTA_COMPLEMENT = 0x10;
constexpr DWORD D3DTA_ALPHAREPLICATE = 0x20;

constexpr DWORD D3DTTFF_DISABLE = 0;
constexpr DWORD D3DTTFF_COUNT1 = 1;
constexpr DWORD D3DTTFF_COUNT2 = 2;
constexpr DWORD D3DTTFF_COUNT3 = 3;
constexpr DWORD D3DTTFF_COUNT4 = 4;
constexpr DWORD D3DTTFF_PROJECTED = 0x100;

constexpr DWORD D3DTSS_TCI_PASSTHRU = 0x00000000;
constexpr DWORD D3DTSS_TCI_CAMERASPACENORMAL = 0x00010000;
constexpr DWORD D3DTSS_TCI_CAMERASPACEPOSITION = 0x00020000;
constexpr DWORD D3DTSS_TCI_CAMERASPACEREFLECTIONVECTOR = 0x00030000;

constexpr DWORD D3DTEXF_NONE = 0;
constexpr DWORD D3DTEXF_POINT = 1;
constexpr DWORD D3DTEXF_LINEAR = 2;
constexpr DWORD D3DTEXF_ANISOTROPIC = 3;
constexpr DWORD D3DTEXF_FLATCUBIC = 4;
constexpr DWORD D3DTEXF_GAUSSIANCUBIC = 5;

constexpr DWORD D3DTEXOPCAPS_DISABLE = 0;
constexpr DWORD D3DTEXOPCAPS_SELECTARG1 = 1u << 0;
constexpr DWORD D3DTEXOPCAPS_MODULATE = 1u << 1;
constexpr DWORD D3DTEXOPCAPS_ADD = 1u << 2;
constexpr DWORD D3DTEXOPCAPS_ADDSMOOTH = 1u << 3;
constexpr DWORD D3DTEXOPCAPS_BLENDTEXTUREALPHA = 1u << 4;
constexpr DWORD D3DTEXOPCAPS_BLENDCURRENTALPHA = 1u << 5;
constexpr DWORD D3DTEXOPCAPS_BUMPENVMAP = 1u << 6;
constexpr DWORD D3DTEXOPCAPS_BUMPENVMAPLUMINANCE = 1u << 7;
constexpr DWORD D3DTEXOPCAPS_DOTPRODUCT3 = 1u << 8;
constexpr DWORD D3DTEXOPCAPS_SUBTRACT = 1u << 9;

constexpr DWORD D3DCOLORWRITEENABLE_RED = 0x1;
constexpr DWORD D3DCOLORWRITEENABLE_GREEN = 0x2;
constexpr DWORD D3DCOLORWRITEENABLE_BLUE = 0x4;
constexpr DWORD D3DCOLORWRITEENABLE_ALPHA = 0x8;

constexpr DWORD D3DMCS_MATERIAL = 0;
constexpr DWORD D3DMCS_COLOR1 = 1;
constexpr DWORD D3DMCS_COLOR2 = 2;

constexpr DWORD D3DCLEAR_TARGET = 0x1;
constexpr DWORD D3DCLEAR_ZBUFFER = 0x2;
constexpr DWORD D3DCLEAR_STENCIL = 0x4;

constexpr DWORD D3DPRASTERCAPS_FOGRANGE = 1u << 0;
constexpr DWORD D3DPRASTERCAPS_ZBIAS = 1u << 1;

constexpr DWORD D3DPTFILTERCAPS_MAGFLINEAR = 1u << 0;
constexpr DWORD D3DPTFILTERCAPS_MINFLINEAR = 1u << 1;
constexpr DWORD D3DPTFILTERCAPS_MIPFLINEAR = 1u << 2;
constexpr DWORD D3DPTFILTERCAPS_MAGFANISOTROPIC = 1u << 3;
constexpr DWORD D3DPTFILTERCAPS_MINFANISOTROPIC = 1u << 4;

constexpr DWORD D3DDEVCAPS_HWTRANSFORMANDLIGHT = 1u << 0;
constexpr DWORD D3DDEVCAPS_NPATCHES = 1u << 1;

constexpr DWORD D3DCAPS2_FULLSCREENGAMMA = 1u << 0;

constexpr DWORD D3DPATCHEDGE_DISCRETE = 0;
constexpr DWORD D3DPATCHEDGE_CONTINUOUS = 1;

constexpr DWORD D3DDMT_ENABLE = 0;
constexpr DWORD D3DDMT_DISABLE = 1;

constexpr DWORD D3DLOCK_READONLY = 0x0010;
constexpr DWORD D3DLOCK_NOOVERWRITE = 0x0100;
constexpr DWORD D3DLOCK_DISCARD = 0x0200;
constexpr DWORD D3DLOCK_NOSYSLOCK = 0x0800;

constexpr DWORD D3DUSAGE_RENDERTARGET = 0x00000001;

constexpr DWORD D3DADAPTER_DEFAULT = 0;
constexpr DWORD D3DBACKBUFFER_TYPE_MONO = 0;
constexpr DWORD D3DMULTISAMPLE_NONE = 0;
constexpr DWORD D3DPRESENT_RATE_DEFAULT = 0;
constexpr DWORD D3DPRESENT_INTERVAL_DEFAULT = 0;
constexpr DWORD D3DPRESENT_INTERVAL_ONE = 1;
constexpr DWORD D3DPRESENT_INTERVAL_TWO = 2;
constexpr DWORD D3DPRESENT_INTERVAL_THREE = 3;
constexpr DWORD D3DPRESENT_INTERVAL_IMMEDIATE = 4;
constexpr DWORD D3DPRESENTFLAG_LOCKABLE_BACKBUFFER = 0x1;
constexpr DWORD D3DENUM_NO_WHQL_LEVEL = 0x2;
constexpr DWORD D3D_SDK_VERSION = 120;

constexpr HRESULT D3D_OK = 0;
constexpr HRESULT D3DERR_DEVICELOST = -2005530519;
constexpr HRESULT D3DERR_DEVICENOTRESET = -2005530520;
constexpr HRESULT D3DERR_NOTAVAILABLE = -2005530518;
constexpr HRESULT D3DERR_OUTOFVIDEOMEMORY = -2005532292;
constexpr HRESULT D3DERR_CONFLICTINGTEXTUREFILTER = -1;
constexpr HRESULT D3DERR_CONFLICTINGTEXTUREPALETTE = -2;
constexpr HRESULT D3DERR_TOOMANYOPERATIONS = -3;
constexpr HRESULT D3DERR_UNSUPPORTEDALPHAARG = -4;
constexpr HRESULT D3DERR_UNSUPPORTEDALPHAOPERATION = -5;
constexpr HRESULT D3DERR_UNSUPPORTEDCOLORARG = -6;
constexpr HRESULT D3DERR_UNSUPPORTEDCOLOROPERATION = -7;
constexpr HRESULT D3DERR_UNSUPPORTEDFACTORVALUE = -8;
constexpr HRESULT D3DERR_UNSUPPORTEDTEXTUREFILTER = -9;
constexpr HRESULT D3DERR_WRONGTEXTUREFORMAT = -10;

constexpr DWORD D3DFVF_XYZ = 0x002;
constexpr DWORD D3DFVF_NORMAL = 0x010;
constexpr DWORD D3DFVF_DIFFUSE = 0x040;
constexpr DWORD D3DFVF_SPECULAR = 0x080;
constexpr DWORD D3DFVF_TEX1 = 0x100;
constexpr DWORD D3DFVF_TEX2 = 0x200;
constexpr DWORD D3DFVF_TEX3 = 0x300;
constexpr DWORD D3DFVF_TEX4 = 0x400;
constexpr DWORD D3DFVF_TEX5 = 0x500;
constexpr DWORD D3DFVF_TEX6 = 0x600;
constexpr DWORD D3DFVF_TEX7 = 0x700;
constexpr DWORD D3DFVF_TEX8 = 0x800;

struct D3DDISPLAYMODE
{
    UINT Width;
    UINT Height;
    UINT RefreshRate;
    D3DFORMAT Format;
};

struct D3DPRESENT_PARAMETERS
{
    UINT BackBufferWidth;
    UINT BackBufferHeight;
    D3DFORMAT BackBufferFormat;
    UINT BackBufferCount;
    UINT MultiSampleType;
    UINT SwapEffect;
    HWND hDeviceWindow;
    BOOL Windowed;
    BOOL EnableAutoDepthStencil;
    D3DFORMAT AutoDepthStencilFormat;
    DWORD Flags;
    UINT FullScreen_RefreshRateInHz;
    UINT FullScreen_PresentationInterval;
};

struct D3DGAMMARAMP
{
    WORD red[256];
    WORD green[256];
    WORD blue[256];
};

struct D3DLOCKED_RECT
{
    int Pitch;
    void *pBits;
};

using D3DRESOURCETYPE = std::uint32_t;

struct D3DSURFACE_DESC
{
    D3DFORMAT Format;
    D3DRESOURCETYPE Type;
    DWORD Usage;
    D3DPOOL Pool;
    UINT Size;
    UINT MultiSampleType;
    UINT Width;
    UINT Height;
};

struct D3DCAPS8
{
    UINT AdapterOrdinal;
    D3DDEVTYPE DeviceType;
    DWORD Caps2;
    DWORD DevCaps;
    DWORD RasterCaps;
    DWORD TextureFilterCaps;
    DWORD TextureOpCaps;
    DWORD MaxTextureWidth;
    DWORD MaxTextureHeight;
    DWORD MaxSimultaneousTextures;
    DWORD VertexShaderVersion;
    DWORD PixelShaderVersion;
};

struct D3DMATRIX
{
    float m[4][4];
};

constexpr D3DRESOURCETYPE D3DRTYPE_SURFACE = 1;
constexpr D3DRESOURCETYPE D3DRTYPE_TEXTURE = 3;

#if RENEGADE_WITH_BGFX_RENDERER
struct IDirect3DBaseTexture8;
struct IDirect3DSurface8;
struct IDirect3DTexture8;
struct IDirect3DSwapChain8;
struct IDirect3D8;
struct IDirect3DDevice8;
#else
struct IDirect3DBaseTexture8
{
    virtual ~IDirect3DBaseTexture8() = default;
    virtual ULONG AddRef() = 0;
    virtual ULONG Release() = 0;
};

struct IDirect3DSurface8
{
    virtual ~IDirect3DSurface8() = default;
    virtual ULONG AddRef() = 0;
    virtual ULONG Release() = 0;
    virtual HRESULT GetDesc(D3DSURFACE_DESC *desc) = 0;
    virtual HRESULT LockRect(D3DLOCKED_RECT *locked_rect, const RECT *rect, DWORD flags) = 0;
    virtual HRESULT UnlockRect() = 0;
};

struct IDirect3DTexture8 : public IDirect3DBaseTexture8
{
    virtual UINT GetLevelCount() = 0;
    virtual HRESULT GetSurfaceLevel(UINT level, IDirect3DSurface8 **surface) = 0;
    virtual HRESULT LockRect(UINT level, D3DLOCKED_RECT *locked_rect, const RECT *rect, DWORD flags) = 0;
    virtual HRESULT UnlockRect(UINT level) = 0;
};

struct IDirect3DSwapChain8;
struct IDirect3D8;
struct IDirect3DDevice8;
#endif

constexpr D3DCOLOR D3DCOLOR_COLORVALUE(float r, float g, float b, float a)
{
    const auto clamp = [](float value) -> std::uint32_t {
        if (value < 0.0f) {
            value = 0.0f;
        } else if (value > 1.0f) {
            value = 1.0f;
        }

        return static_cast<std::uint32_t>(value * 255.0f + 0.5f);
    };

    return (clamp(a) << 24) | (clamp(r) << 16) | (clamp(g) << 8) | clamp(b);
}
