include_guard(GLOBAL)

set(_renegade_supported_build_types Debug RelWithDebInfo)

if(CMAKE_CONFIGURATION_TYPES)
    set(CMAKE_CONFIGURATION_TYPES "Debug;RelWithDebInfo" CACHE STRING "Supported build configurations" FORCE)
else()
    set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS ${_renegade_supported_build_types})
    if(NOT CMAKE_BUILD_TYPE)
        set(CMAKE_BUILD_TYPE "Debug" CACHE STRING "Choose the build type" FORCE)
    endif()
endif()

option(RENEGADE_WITH_SDL3 "Use vendored SDL3 for platform abstractions" ON)
set(RENEGADE_AUDIO_BACKEND "SDL_MIXER" CACHE STRING "Audio backend to use")
set_property(CACHE RENEGADE_AUDIO_BACKEND PROPERTY STRINGS "SDL_MIXER" "NULL")
option(RENEGADE_WITH_X86_ASM "Enable legacy x86 assembly implementations" OFF)
option(RENEGADE_WITH_UMBRA "Enable Umbra integration" OFF)
option(RENEGADE_WITH_BINK "Enable Bink movie playback" ON)
option(RENEGADE_WITH_MILES "Enable Miles audio integration" OFF)
option(RENEGADE_WITH_GAMESPY "Enable GameSpy integration" OFF)
option(RENEGADE_WITH_LEGACY_WOL "Enable legacy WOL integration" OFF)
option(RENEGADE_WITH_DX8_RENDERER "Enable the legacy DirectX 8 renderer" OFF)
option(RENEGADE_WITH_BGFX_RENDERER "Enable the bgfx renderer backend" ON)
option(RENEGADE_WITH_BANDTEST "Enable the historical BandTest dependency" OFF)
option(RENEGADE_WITH_SCONTROL "Enable the historical SControl dependency" OFF)
option(RENEGADE_ENABLE_ASAN "Instrument Renegade targets with AddressSanitizer" OFF)
option(RENEGADE_ENABLE_UBSAN "Instrument Renegade targets with UndefinedBehaviorSanitizer" OFF)
option(RENEGADE_ENABLE_TSAN "Instrument Renegade targets with ThreadSanitizer" OFF)
